apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pro-bmw-console
  namespace: pro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pro-bmw-console
    spec:
      containers:
        - name: pro-bmw-console
          image: registry.cn-beijing.aliyuncs.com/bmwpoc/pro-bmw-console:{version}
          ports:
            - name: http-port
              containerPort: 8080
      imagePullSecrets:
        - name: bmwpoc