apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sit-bmw-console
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sit-bmw-console
    spec:
      containers:
        - name: sit-bmw-console
          image: registry.cn-beijing.aliyuncs.com/bmwpoc/sit-bmw-console:{version}
          ports:
            - name: http-port
              containerPort: 80
      imagePullSecrets:
        - name: bmwpoc